language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "api-spring-hateoas"
    token:
      secure: "8f51ae1885c5ae4d87a3261b448ba0b6a405075a" # encrypted value of your token
jdk:
  - openjdk11
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'